Update reason for duplicates checking
AY2425S1-CS2103T-F14a-1/tp pull request #181
Opened 2024-10-26 13:40 UTC by DennieDan

Closes #158 #171 
This PR
- Updates reason for duplicates checking
- Change the box of **Features** from `seamless` to normal. Can view the following pic and let me know if you prefer this or the old one
![image](https://github.com/user-attachments/assets/18f008a3-79fd-4e66-a5b6-1a20546a6e77)

2024-10-27 01:58 UTC, Soumyadip-cmd approved these changes
LGTM. Thanks for spotting the mistakes and changing them. You could perhaps put the bug label on this PR.

2024-10-27 01:58 UTC, Soumyadip-cmd commented on docs/UserGuide.md
> +Shows a message explaining how to access the help page.
Good catch👍. Thanks for changing this.

2024-10-27 01:58 UTC, Soumyadip-cmd commented on docs/UserGuide.md
> +  e.g `n/NAME [owe/OWED_AMOUNT]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
Thanks for changing this too

2024-10-27 02:47 UTC, DennieDan commented
> LGTM. Thanks for spotting the mistakes and changing them. You could perhaps put the bug label on this PR.

Sure, I will

2024-10-27 04:40 UTC, Feng1231 requested changes
Nice, but need to update the example too

2024-10-27 04:40 UTC, Feng1231 commented on docs/UserGuide.md
> +  e.g `n/NAME [owe/OWED_AMOUNT]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
hmm, t/TAG is removed be the examples not updated yet! 😢 
> `n/John Doe t/friend` or as `n/John Doe`.

These are still using PREFIX_TAG, right?

2024-10-27 04:40 UTC, Feng1231 commented on docs/UserGuide.md
>  * Extraneous parameters for commands that do not take in parameters (such as `help`, `list`, `exit` and `clear`) will be ignored.<br>
This part should include all the new commands too.
income, remind, and others if I miss out any.
Perhaps we should create another issue for it

2024-10-27 04:40 UTC, Feng1231 commented on docs/UserGuide.md
> +* No two students can have both same **NAME** and **PHONE**, but different students may share a **PHONE** number.
the parameters provided is PHONE_NUMBER in this case, should we just standardize to just refer to **PHONE_NUMBER**

2024-10-28 06:40 UTC, Feng1231 approved these changes
LGTM

2024-10-28 13:13 UTC, merged