Previously, did not add tests to for income command
AY2425S1-CS2103T-F14a-1/tp pull request #85
Opened 2024-10-13 12:54 UTC by teamotitan

Added tests for income command, as well as fix a few bugs from IncomeCommand

2024-10-14 01:41 UTC, Soumyadip-cmd approved these changes
LGTM

2024-10-14 10:05 UTC, Feng1231 requested changes
LGTM. But you missed out on AddressBookParser test for IncomCommand

2024-10-14 10:05 UTC, Feng1231 commented on src/main/java/seedu/address/logic/commands/IncomeCommand.java
> +        double totalOwed = 0;
Good that you changed it to double!

2024-10-15 09:45 UTC, Feng1231 requested changes

2024-10-15 09:45 UTC, Feng1231 commented on src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> +        assertTrue(parser.parseCommand(ListCommand.COMMAND_WORD + " 3") instanceof ListCommand);
line 95 looks weird. You meant to test 'income 3'?

2024-10-17 04:35 UTC, Soumyadip-cmd approved these changes
LGTM

2024-10-17 09:29 UTC, Feng1231 approved these changes
Nice, thanks for the changes

2024-10-17 09:34 UTC, merged